# Funding links shown in the repo's "Sponsor" button.
# https://docs.github.com/sponsors/receiving-sponsorships-through-github-sponsors/displaying-a-sponsor-button-in-your-repository
github: excom-dev
